import typography from '@tailwindcss/typography'
import tailwindcssAnimate from 'tailwindcss-animate'

/** @type {import('tailwindcss').Config} */
const config = {
  darkMode: ['class'],
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    container: {
      center: true,
      padding: '2rem',
      screens: {
        '2xl': '1400px',
      },
    },
    extend: {
      screens: {
        desktop: '1440px',
      },
      fontFamily: {
        sans: ['var(--font-space-grotesk)', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        display: ['var(--font-space-grotesk)', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        mono: ['var(--font-jetbrains-mono)', 'ui-monospace', 'monospace'],
      },
      colors: {
        neutral: {
          50: 'hsl(var(--neutral-50))',
          100: 'hsl(var(--neutral-100))',
          200: 'hsl(var(--neutral-200))',
          300: 'hsl(var(--neutral-300))',
          400: 'hsl(var(--neutral-400))',
          500: 'hsl(var(--neutral-500))',
          600: 'hsl(var(--neutral-600))',
          700: 'hsl(var(--neutral-700))',
          800: 'hsl(var(--neutral-800))',
          900: 'hsl(var(--neutral-900))',
          950: 'hsl(var(--neutral-950))',
        },
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        primary: {
          DEFAULT: 'hsl(var(--primary))',
          foreground: 'hsl(var(--primary-foreground))',
        },
        secondary: {
          DEFAULT: 'hsl(var(--secondary))',
          foreground: 'hsl(var(--secondary-foreground))',
        },
        destructive: {
          DEFAULT: 'hsl(var(--destructive))',
          foreground: 'hsl(var(--destructive-foreground))',
        },
        muted: {
          DEFAULT: 'hsl(var(--muted))',
          foreground: 'hsl(var(--muted-foreground))',
        },
        accent: {
          DEFAULT: 'hsl(var(--accent))',
          foreground: 'hsl(var(--accent-foreground))',
        },
        popover: {
          DEFAULT: 'hsl(var(--popover))',
          foreground: 'hsl(var(--popover-foreground))',
        },
        card: {
          DEFAULT: 'hsl(var(--card))',
          foreground: 'hsl(var(--card-foreground))',
        },
        success: 'hsl(var(--success))',
        warning: 'hsl(var(--warning))',
        error: 'hsl(var(--error))',
        info: 'hsl(var(--info))',
        'void-black': {
          50: 'hsl(var(--void-black-50))',
          100: 'hsl(var(--void-black-100))',
          200: 'hsl(var(--void-black-200))',
          300: 'hsl(var(--void-black-300))',
          400: 'hsl(var(--void-black-400))',
          500: 'hsl(var(--void-black-500))',
          600: 'hsl(var(--void-black-600))',
          700: 'hsl(var(--void-black-700))',
          800: 'hsl(var(--void-black-800))',
          900: 'hsl(var(--void-black-900))',
          950: 'hsl(var(--void-black-950))',
          DEFAULT: 'hsl(var(--void-black))',
        },
        obsidian: {
          50: 'hsl(var(--obsidian-50))',
          100: 'hsl(var(--obsidian-100))',
          200: 'hsl(var(--obsidian-200))',
          300: 'hsl(var(--obsidian-300))',
          400: 'hsl(var(--obsidian-400))',
          500: 'hsl(var(--obsidian-500))',
          600: 'hsl(var(--obsidian-600))',
          700: 'hsl(var(--obsidian-700))',
          800: 'hsl(var(--obsidian-800))',
          900: 'hsl(var(--obsidian-900))',
          950: 'hsl(var(--obsidian-950))',
          DEFAULT: 'hsl(var(--obsidian))',
        },
        gunmetal: {
          50: 'hsl(var(--gunmetal-50))',
          100: 'hsl(var(--gunmetal-100))',
          200: 'hsl(var(--gunmetal-200))',
          300: 'hsl(var(--gunmetal-300))',
          400: 'hsl(var(--gunmetal-400))',
          500: 'hsl(var(--gunmetal-500))',
          600: 'hsl(var(--gunmetal-600))',
          700: 'hsl(var(--gunmetal-700))',
          800: 'hsl(var(--gunmetal-800))',
          900: 'hsl(var(--gunmetal-900))',
          950: 'hsl(var(--gunmetal-950))',
          DEFAULT: 'hsl(var(--gunmetal))',
        },
        titanium: {
          50: 'hsl(var(--titanium-50))',
          100: 'hsl(var(--titanium-100))',
          200: 'hsl(var(--titanium-200))',
          300: 'hsl(var(--titanium-300))',
          400: 'hsl(var(--titanium-400))',
          500: 'hsl(var(--titanium-500))',
          600: 'hsl(var(--titanium-600))',
          700: 'hsl(var(--titanium-700))',
          800: 'hsl(var(--titanium-800))',
          900: 'hsl(var(--titanium-900))',
          950: 'hsl(var(--titanium-950))',
          DEFAULT: 'hsl(var(--titanium))',
        },
        ash: {
          50: 'hsl(var(--ash-50))',
          100: 'hsl(var(--ash-100))',
          200: 'hsl(var(--ash-200))',
          300: 'hsl(var(--ash-300))',
          400: 'hsl(var(--ash-400))',
          500: 'hsl(var(--ash-500))',
          600: 'hsl(var(--ash-600))',
          700: 'hsl(var(--ash-700))',
          800: 'hsl(var(--ash-800))',
          900: 'hsl(var(--ash-900))',
          950: 'hsl(var(--ash-950))',
          DEFAULT: 'hsl(var(--ash))',
        },
        'arcly-blue': {
          50: 'hsl(var(--arcly-blue-50))',
          100: 'hsl(var(--arcly-blue-100))',
          200: 'hsl(var(--arcly-blue-200))',
          300: 'hsl(var(--arcly-blue-300))',
          400: 'hsl(var(--arcly-blue-400))',
          500: 'hsl(var(--arcly-blue-500))',
          600: 'hsl(var(--arcly-blue-600))',
          700: 'hsl(var(--arcly-blue-700))',
          800: 'hsl(var(--arcly-blue-800))',
          900: 'hsl(var(--arcly-blue-900))',
          950: 'hsl(var(--arcly-blue-950))',
          DEFAULT: 'hsl(var(--arcly-blue))',
        },
        'signal-green': {
          50: 'hsl(var(--signal-green-50))',
          100: 'hsl(var(--signal-green-100))',
          200: 'hsl(var(--signal-green-200))',
          300: 'hsl(var(--signal-green-300))',
          400: 'hsl(var(--signal-green-400))',
          500: 'hsl(var(--signal-green-500))',
          600: 'hsl(var(--signal-green-600))',
          700: 'hsl(var(--signal-green-700))',
          800: 'hsl(var(--signal-green-800))',
          900: 'hsl(var(--signal-green-900))',
          950: 'hsl(var(--signal-green-950))',
          DEFAULT: 'hsl(var(--signal-green))',
        },
        'alert-red': {
          50: 'hsl(var(--alert-red-50))',
          100: 'hsl(var(--alert-red-100))',
          200: 'hsl(var(--alert-red-200))',
          300: 'hsl(var(--alert-red-300))',
          400: 'hsl(var(--alert-red-400))',
          500: 'hsl(var(--alert-red-500))',
          600: 'hsl(var(--alert-red-600))',
          700: 'hsl(var(--alert-red-700))',
          800: 'hsl(var(--alert-red-800))',
          900: 'hsl(var(--alert-red-900))',
          950: 'hsl(var(--alert-red-950))',
          DEFAULT: 'hsl(var(--alert-red))',
        },
        linen: {
          DEFAULT: 'hsl(var(--linen))',
        },
        parchment: {
          DEFAULT: 'hsl(var(--parchment))',
        },
        sandstone: {
          DEFAULT: 'hsl(var(--sandstone))',
        },
        ink: {
          DEFAULT: 'hsl(var(--ink))',
        },
      },
      borderRadius: {
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)',
      },
      keyframes: {
        'accordion-down': {
          from: { height: 0 },
          to: { height: 'var(--radix-accordion-content-height)' },
        },
        'accordion-up': {
          from: { height: 'var(--radix-accordion-content-height)' },
          to: { height: 0 },
        },
      },
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
      },
    },
  },
  plugins: [tailwindcssAnimate, typography],
}

export default config
